export const POST_REGISTER_SUCCESSFUL = "POST_REGISTER_SUCCESSFUL";
export const POST_REGISTER_FAILED = "POST_REGISTER_FAILED";
export const POST_REGISTER_RESET = "POST_REGISTER_RESET";

export const POST_LOGIN_SUCCESSFUL = "POST_LOGIN_SUCCESSFUL";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";
